// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCFKdFziXt7j7wsoCHZ1nWChoKsy6cCj8U",
    // apiKey: 'AIzaSyDb_zz0woAHGNq8W1RlU-0giJaT3vstJ44',
    appId: '1:1000407154647:web:0cc6c26e11d212a233d592',
    messagingSenderId: '1000407154647',
    projectId: 'procounsellor-71824',
    authDomain: 'procounsellor-71824.firebaseapp.com',
    databaseURL: 'https://procounsellor-71824-default-rtdb.firebaseio.com',
    storageBucket: 'procounsellor-71824.firebasestorage.app',
    measurementId: 'G-B3YPBQMY6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqfjggLNBAT7QT-2hELQdobq-ffCrFg8',
    appId: '1:1000407154647:android:b968b3946ced762c33d592',
    messagingSenderId: '1000407154647',
    projectId: 'procounsellor-71824',
    databaseURL: 'https://procounsellor-71824-default-rtdb.firebaseio.com',
    storageBucket: 'procounsellor-71824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCidO9Sob0vAARTb-JmtXy30MTYOSDI3y0',
    appId: '1:1000407154647:ios:9b04ad16280d918c33d592',
    messagingSenderId: '1000407154647',
    projectId: 'procounsellor-71824',
    databaseURL: 'https://procounsellor-71824-default-rtdb.firebaseio.com',
    storageBucket: 'procounsellor-71824.firebasestorage.app',
    iosBundleId: 'com.catalyst.ProCounsellor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCidO9Sob0vAARTb-JmtXy30MTYOSDI3y0',
    appId: '1:1000407154647:ios:1a990f89804f2c6133d592',
    messagingSenderId: '1000407154647',
    projectId: 'procounsellor-71824',
    databaseURL: 'https://procounsellor-71824-default-rtdb.firebaseio.com',
    storageBucket: 'procounsellor-71824.firebasestorage.app',
    iosBundleId: 'com.catalyst.ProCounsellor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCFKdFziXt7j7wsoCHZ1nWChoKsy6cCj8U",
    // apiKey: 'AIzaSyDb_zz0woAHGNq8W1RlU-0giJaT3vstJ44',
    appId: '1:1000407154647:web:330a3bc5a11e8e9933d592',
    messagingSenderId: '1000407154647',
    projectId: 'procounsellor-71824',
    authDomain: 'procounsellor-71824.firebaseapp.com',
    databaseURL: 'https://procounsellor-71824-default-rtdb.firebaseio.com',
    storageBucket: 'procounsellor-71824.firebasestorage.app',
    measurementId: 'G-3SD403BVLF',
  );
}
